config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get '/about', to: 'pages#about', as: 'about'
  get '/join', to: 'users#new', as: 'join'
  post '/join', to: 'users#create', as: 'users'
  
  get '/login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/venues', to: 'venues#public_index', as: 'public_venues' 
  get '/venues/:id', to: 'venues#show', as: 'venue'

  get '/events', to: 'events#public_index', as: 'public_events' 
  resources :events, only: [:show] do
    resources :posts, only: [:create, :update, :destroy]
  end

  resources :users, param: :username, path: '/', except: [:index, :create, :new] do
  	resources :events, except: [:edit, :show] do
      get '/manage/:step', to: 'events#manage', as: 'manage'
      post '/guests', to: 'events#add_guests', as: 'add_guests'
      post '/invite', to: 'events#send_invites', as: 'send_invites'
      delete '/guests/:id', to: 'events#remove_guest', as: 'remove_guest'
      get '/location/:id', to: 'events#preview_venue', as: 'preview_venue'
      post '/location/:id', to: 'events#select_venue', as: 'select_venue'
      delete 'location/:id', to: 'events#remove_venue', as: 'remove_venue'
    end
  	resources :venues, except: [:edit, :show] do
      get '/manage/:step', to: 'venues#manage', as: 'manage'
      post '/photos', to: 'venues#update_photos', as: 'update_photos'
      delete '/photos/:id', to: 'venues#remove_photo', as: 'remove_photo'
      post '/tags', to: 'venues#update_tags', as: 'update_tags'
    end
    resources :photos, only: [:create, :destroy]
    get '/events/:id', to: 'events#stats', as: 'event_stats'
    get '/venues/:id', to: 'venues#stats', as: 'venue_stats'
    get '/tell-me-more', to: 'profiles#edit', as: 'profile'
    post '/tell-me-more', to: 'profiles#update', as: 'update_profile'
    post '/rsvp/:id', to: 'users#rsvp', as: 'rsvp'
  end

  get '/review/:attendance_id', to: 'feedbacks#rate_event_and_venue', as: 'feedback'
  post '/review/:attendance_id', to: 'feedbacks#submit', as: 'submit_feedback'

  root 'pages#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  email           :string           not null
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  username        :string
#  remember_digest :string
#
# Indexes
#
#  index_users_on_username  (username) UNIQUE
#

class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	attr_accessor :remember_token
	has_secure_password

	has_many :events
	has_many :venues
	has_many :attendances
	has_many :posts, dependent: :destroy
	has_many :venue_feedbacks, through: :attendances
	has_many :event_feedbacks, through: :attendances
	has_many :photos, foreign_key: "owner_id"
	has_many :notifications
	has_one :photo, as: :pictureable
	has_one :profile

	accepts_nested_attributes_for :photo

	validates :first_name, presence: true
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, 
										uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }, on: :create

	before_save { self.email.downcase! }
	after_create_commit { self.create_profile }

	def to_param
		username
	end

	def full_name
    if last_name.blank?
      first_name
    else
      "#{first_name} #{last_name}"
    end
  end

  def profile_picture
  	if @photo = self.photo
  		@photo.image_file_name_url :thumb
  	else
      "heart.png"
    end
  end

	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def remember
    self.remember_token = User.new_remember_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

	def forget
    update_attribute(:remember_digest, nil)
  end

  def unread_notifications?
  	self.notifications.where(is_viewed: false).any?
  end

end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  email           :string           not null
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  username        :string
#  remember_digest :string
#
# Indexes
#
#  index_users_on_username  (username) UNIQUE
#

class UsersController < ApplicationController
	before_action :logged_in_user, :correct_user, except: [:index, :new, :create, :rsvp]

	def show
		@user = User.find_by_username(params[:username])
		@upcoming_atts , @past_atts = [], []
		@user.attendances.each do |att|
			@upcoming_atts << att if att.event.end_time > DateTime.now
			@past_atts << att if (att.rsvp == 'attending' && att.event.end_time < DateTime.now)
		end
	end

	def index
		@users = User.all
		render json: @users
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Thanks for joining PlaceCard!"
			redirect_back_or @user
		else
			render 'new'
		end
	end

	def edit
		@user = User.find_by_username(params[:username])
	end

	def update
		@user = User.find_by_username(params[:username])
		@old_photo = @user.photo
		if !photo_params[:photo].blank? 
			if @user.photos.create!(image_file_name: photo_params[:photo], pictureable: @user, is_profile: true)
				@old_photo.destroy! if @old_photo
			end
		end
		if @user.update_attributes(user_params)
		  flash[:success] = "Data saved."
      redirect_to @user
		else
			flash.now[:danger] = "Certain fields are required."
		  render 'edit'
		end
  end

  def destroy
    User.find_by_username(params[:username]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def rsvp
  	@attendance = Attendance.find(params[:id])
  	if Attendance::RSVP.include?(rsvp_params[:rsvp]) && @attendance.update_attributes(rsvp_params)
  		redirect_back_or current_user
  	end
  end

	private

		def user_params
			params.require(:user).permit(:first_name, :last_name, :username, :email, :password, :password_confirmation)
		end

		def photo_params
			params.require(:photo)
		end

		def rsvp_params
			params.permit(:rsvp)
		end

		def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find_by_username(params[:username])
      redirect_to(root_url) unless current_user?(@user)
    end
	
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  email           :string           not null
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  username        :string
#  remember_digest :string
#
# Indexes
#
#  index_users_on_username  (username) UNIQUE
#

module UsersHelper

	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
  end

end

app/views/users/_events.html.erb
<table class="table table-hover">
	<% @user.events.each do |event| %>
	<tr>
		<th> <%= link_to event.title, event%> </th>
		<th> <%= link_to "Edit", user_event_manage_path(@user, event.id, "basics"), class: "btn btn-primary",style: "float: right;"  %> </th>
		<th> <%= link_to "Delete",  user_event_path(@user, event), method: :delete, data: 
						{confirm: "Are you sure you want to delete this event?" }, class: "btn btn-primary ", style: "float: right;" %> </th>
	</tr>
	<% end %>
</table>

app/views/users/_sidebar.html.erb
<div class="col-sm-3 sidebar">

  <div class="sheet sheet-column">
  <div class="row">
  <div class="nav nav-sidebar">
    <div class="text-center">
      <%= image_tag (current_user.profile_picture), class: 'img-thumbnail img-circle', size: '100' %>
      <h3> <%= current_user.full_name %> </h3>
    </div>
    <li>
      <a href="<%= user_path(current_user) %>" class="<%= 'active' if request.fullpath == user_path(current_user) %>">
        <span class="">Home</span>
      </a> 
    </li>
    <li>
      <a href="<%= user_events_path(current_user) %>" class="<%= 'active' if request.fullpath == user_events_path(current_user) %>">
        <span>My Events</span>
        <span class="pull-right label label-warning"> <%= @user.events.count %> </span>
      </a> 
    </li>
    <li>
      <a href="<%= user_venues_path(current_user) %>" class="<%= 'active' if request.fullpath == user_venues_path(current_user) %>">
        <span>My Venues</span>
        <span class="pull-right label label-warning"> <%= @user.venues.count %> </span>
      </a> 
    </li>
  </div>
  </div>
  <!-- @TODO add sticky-bottom if the user has not completed their demographics profile -->
  <div class="nag">
    <h5>Make PlaceCard better by adding more personal information.</h5>
    <%= link_to "Tell us more", user_profile_path(current_user), class: 'btn btn-warning' %>
  </div>
  </div>

</div>

app/views/users/edit.html.erb
<div class="sheet">

  <%= render partial: 'sidebar' %>
  
  <div class="flex-content">
    <div class="col-md-6 col-md-offset-3">
      <div class="row">

        <%= form_for @user do |f| %>
        
          <div class="text-center">
            <h1><%= @user.first_name + " " + @user.last_name %></h1>
          </div>

          <div class="row">
            <div class="col-xs-6">
              <div class="form-group">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: 'form-control' %>
              </div> <!-- close .form-group -->
            </div> <!-- close .col -->

            <div class="col-xs-6">
              <div class="form-group">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: 'form-control' %>
              </div> <!-- close .form-group -->
            </div> <!-- close .col -->
          </div> <!-- close .row -->

          <div class="form-group">
            <%= f.label :email do %>
              Email address
            <% end %>
            <%= f.email_field :email, class: 'form-control' %>
          </div> <!-- close .form-group -->

          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, class: 'form-control' %>
          </div> <!-- close .form-group -->

          <div class="form-group">
            <%= f.submit 'Update', class: 'btn btn-outline btn-default btn-block-level' %>

            <%= fields_for @user.photos, method: :post do |p| %>
              <span class="btn btn-outline btn-default fileinput-button">
                <span class="glyphicon glyphicon-camera"></span>
                <span>Change profile</span>
                <%= p.file_field "photo", multiple: false, id: "jq_photo" %>
              </span>
            <% end %>
          </div>

        <% end %>

      </div> <!-- close .row -->
    </div>
  </div>

</div>

app/views/users/new.html.erb
<% set_page_title "Sign up" %>

<div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">

    <h2 class="text-center">Already joined? <%= link_to "Login", login_path %></h2>
    <div class="form">
      <%= form_for @user, validate: true do |f| %>

        <div class="row">
          <div class="col-xs-6">
            <div class="form-group">
              <%= f.label :first_name %>
              <%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
            </div> <!-- close .form-group -->
          </div> <!-- close .col -->

          <div class="col-xs-6">
            <div class="form-group">
              <%= f.label :last_name %>
              <%= f.text_field :last_name, class: 'form-control' %>
            </div> <!-- close .form-group -->
          </div> <!-- close .col -->
        </div> <!-- close .row -->

        <div class="form-group">
          <%= f.label :email do %>
            Email address
          <% end %>

          <%= f.email_field :email, class: 'form-control' %>
        </div> <!-- close .form-group -->

        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, class: 'form-control' %>
        </div> <!-- close .form-group -->

        <div class="form-group">
          <%= f.label :password do %>
            Password <span class="text-secondary">(min. 6 char)</span>
          <% end %>
          
          <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
        </div> <!-- close .form-group -->

        <div class="form-group">
        	<%= f.label :password_confirmation do %>
        		Password confirmation
        	<% end %>
        	<%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit "Sign up", class: 'btn btn-outline btn-block-level' %>
        </div> <!-- close .form-group -->
      <% end %>
    </div> <!-- close .form -->

  </div> <!-- close .col -->
</div> <!-- close .row -->

<div class="row text-center">
  <%= link_to 'Home', root_path %>
</div> <!-- close .text-center -->

app/views/users/show.html.erb
<div class="sheet">
	
	<!-- sidebar is 3-col wide -->
	<%= render partial: 'sidebar' %>

	<!-- yield content once this is a layout -->
	<div class="flex-content">
		<div class="sheet sheet-column">

			<div class="panel panel-default">
				<div class="panel-heading">
				 	Pending invitations &amp; upcoming events
				</div>
				<table class="table table-hover">
					<% @upcoming_atts.each do |upcoming| %>
						<tr>
							<th><%= link_to upcoming.event.title, upcoming.event %></th>
							<td><%= link_to "Going", user_rsvp_path(@user.username, upcoming.id, rsvp: :attending), method: 'post',
															 class: "label label-default #{'label-success' if upcoming.rsvp == 'attending' }" %></td>
							<td><%= link_to "Not going", user_rsvp_path(@user.username, upcoming.id, rsvp: :not_attending), method: 'post',
															 class: "label label-default #{'label-warning' if upcoming.rsvp == 'not_attending' }" %></td>
							<td><%= link_to "Maybe", user_rsvp_path(@user.username, upcoming.id, rsvp: :unsure), method: 'post',
															 class: "label label-default #{'label-info' if upcoming.rsvp == 'unsure' }" %></td>
						</tr>
					<% end %>
					<% if !@upcoming_atts.any? %>
						<tr>
							<th> <a>You don't have any upcoming events.</a> </th>
							<td> <%= link_to "Create one?", new_user_event_path(@user.username), class: 'label btn-primary' %> </td>
						</tr>
					<% end %>
				</table>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
				 	Past events
				</div>
				<table class="table table-hover">
					<% @past_atts.each do |past| %>
						<tr>
							<th><%= link_to past.event.title, past.event %></th>
							<th><%= %></th>
							<th><%= %></th>
						</tr>
					<% end %>
					<% if !@past_atts.any? %>
						<tr>
							<td> No past events to show at this time. </td>
						</tr>
					<% end %>
				</table>
			</div>

		</div>
	</div>

</div>