config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get '/about', to: 'pages#about', as: 'about'
  get '/join', to: 'users#new', as: 'join'
  post '/join', to: 'users#create', as: 'users'
  
  get '/login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/venues', to: 'venues#public_index', as: 'public_venues' 
  get '/venues/:id', to: 'venues#show', as: 'venue'

  get '/events', to: 'events#public_index', as: 'public_events' 
  resources :events, only: [:show] do
    resources :posts, only: [:create, :update, :destroy]
  end

  resources :users, param: :username, path: '/', except: [:index, :create, :new] do
  	resources :events, except: [:edit, :show] do
      get '/manage/:step', to: 'events#manage', as: 'manage'
      post '/guests', to: 'events#add_guests', as: 'add_guests'
      post '/invite', to: 'events#send_invites', as: 'send_invites'
      delete '/guests/:id', to: 'events#remove_guest', as: 'remove_guest'
      get '/location/:id', to: 'events#preview_venue', as: 'preview_venue'
      post '/location/:id', to: 'events#select_venue', as: 'select_venue'
      delete 'location/:id', to: 'events#remove_venue', as: 'remove_venue'
    end
  	resources :venues, except: [:edit, :show] do
      get '/manage/:step', to: 'venues#manage', as: 'manage'
      post '/photos', to: 'venues#update_photos', as: 'update_photos'
      delete '/photos/:id', to: 'venues#remove_photo', as: 'remove_photo'
      post '/tags', to: 'venues#update_tags', as: 'update_tags'
    end
    resources :photos, only: [:create, :destroy]
    get '/events/:id', to: 'events#stats', as: 'event_stats'
    get '/venues/:id', to: 'venues#stats', as: 'venue_stats'
    get '/tell-me-more', to: 'profiles#edit', as: 'profile'
    post '/tell-me-more', to: 'profiles#update', as: 'update_profile'
    post '/rsvp/:id', to: 'users#rsvp', as: 'rsvp'
  end

  get '/review/:attendance_id', to: 'feedbacks#rate_event_and_venue', as: 'feedback'
  post '/review/:attendance_id', to: 'feedbacks#submit', as: 'submit_feedback'

  root 'pages#index'

end

app/views/shared/_flashes.html.erb
<div class="container" id="flashes">
	<% flash.each do |key, value| %>
	  <div class="alert alert-<%= key %> alert-dismissable fade in">
	    <%= content_tag(:span, value) %>
	    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  </div> <!-- close .alert -->
	<% end %>
</div>

app/views/shared/_head.html.erb
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title>
  <% if content_for?(:page_title) %>    
    <%= yield(:page_title) %>
  <% else %>
    PlaceCard
  <% end %>
</title>

<meta name="description" content="
  <% if content_for?(:page_description) %>
    <%= yield(:page_description) %>
  <% else %>
    Find the right venue for your event. Organize your wedding, conference, party, or workshop, and easily communicate with guests - totally free.
  <% end %>
">
<meta name="author" content="Saige McVea, Gabriela Stefanini, Kathryn Taylor, Zili Zhang">
<%= csrf_meta_tags %>
<%= action_cable_meta_tag %>
<%= favicon_link_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

app/views/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar" id="placecard-nav">
	<div class="container-fluid">
		
		<div class="navbar-header navbar-img" >
			<a id="brand" href="<%= root_path %>">
				<% if controller_name == 'pages' && action_name == 'index' %>
					<%= image_tag "logo_alt.png", height: "100%", alt: "PlaceCard" %>
				<% else %>
					<%= image_tag "icon.png", height: "100%", alt: "PlaceCard" %>
				<% end %>
			</a>
		</div>
		
		<% unless controller_name == 'pages' && action_name == 'index' %>
			<%= form_tag url_for(controller: "venues", action: "public_index"), method: "get", class: "navbar-form navbar-left" do %>
				<%= text_field_tag :search, params[:search], class: "form-control search", placeholder: "Search for a venue" %>
			<% end %>
		<% end %>

		<!-- @TODO Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">

				<% if logged_in? %>

					<li> <%= link_to "List a venue", new_user_venue_path(@current_user), class: "btn btn-outline navbar-btn" %> </li>
					<li> <%= link_to "Create an event", new_user_event_path(@current_user), class: "btn btn-outline navbar-btn" %> </li>
					<li>
						<div class="btn btn-outline navbar-btn <%= 'btn-success' if current_user.event_feedbacks.any? %>" id="quick-links" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
						</div>
						<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="quick-links" id="feedback">
							<%= render partial: 'feedbacks/event_feedback', collection: current_user.event_feedbacks, as: :event_feedback %>
							<% if !current_user.event_feedbacks.any? %>
		          	<li> <a>No reviews at this time.</a> </li>
		          <% end %>
		        </ul>
					</li>
					<li>
						<div class="btn btn-outline navbar-btn <%= 'btn-warning' if current_user.unread_notifications? %>" id="notifs-dropdown" 
							 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="glyphicon glyphicon-flash" aria-hidden="true"></span>
						</div>
						<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="notifs-dropdown" id="notifications">
							<%= render current_user.notifications.reverse %>
		          <% if !current_user.unread_notifications? %>
		          	<li> <a>Up to date!</a> </li>
		          <% end %>
		        </ul>
					</li>
					<li>
						<div class="navbar-img" id="user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<div id="avatar">
								<%= image_tag (current_user.profile_picture), class: 'gravatar' %>
							</div>
						</div>
						<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown" id="account">
		          <li> <%= link_to "Dashboard", user_path(@current_user) %> </li>
		          <li> <%= link_to "Account", edit_user_path(@current_user) %> </li>
		          <li> <%= link_to "Logout", logout_path(@current_user), method: :delete %> </li>
		        </ul> <!-- close .btn dropdown menu -->
		      </li>

				<% else %>

					<li> <%= link_to "Browse venues", public_venues_path, class: "btn btn-outline navbar-btn" %> </li>
					<li> <%= link_to "Login", login_path, class: "btn btn-outline navbar-btn" %> </li>
					<li> <%= link_to "Sign up", join_path, class: "btn btn-outline navbar-btn btn-primary" %> </li>

				<% end %>
			</ul>
		</div>
	</div> <!-- close .container-fluid -->
</nav>