config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get '/about', to: 'pages#about', as: 'about'
  get '/join', to: 'users#new', as: 'join'
  post '/join', to: 'users#create', as: 'users'
  
  get '/login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/venues', to: 'venues#public_index', as: 'public_venues' 
  get '/venues/:id', to: 'venues#show', as: 'venue'

  get '/events', to: 'events#public_index', as: 'public_events' 
  resources :events, only: [:show] do
    resources :posts, only: [:create, :update, :destroy]
  end

  resources :users, param: :username, path: '/', except: [:index, :create, :new] do
  	resources :events, except: [:edit, :show] do
      get '/manage/:step', to: 'events#manage', as: 'manage'
      post '/guests', to: 'events#add_guests', as: 'add_guests'
      post '/invite', to: 'events#send_invites', as: 'send_invites'
      delete '/guests/:id', to: 'events#remove_guest', as: 'remove_guest'
      get '/location/:id', to: 'events#preview_venue', as: 'preview_venue'
      post '/location/:id', to: 'events#select_venue', as: 'select_venue'
      delete 'location/:id', to: 'events#remove_venue', as: 'remove_venue'
    end
  	resources :venues, except: [:edit, :show] do
      get '/manage/:step', to: 'venues#manage', as: 'manage'
      post '/photos', to: 'venues#update_photos', as: 'update_photos'
      delete '/photos/:id', to: 'venues#remove_photo', as: 'remove_photo'
      post '/tags', to: 'venues#update_tags', as: 'update_tags'
    end
    resources :photos, only: [:create, :destroy]
    get '/events/:id', to: 'events#stats', as: 'event_stats'
    get '/venues/:id', to: 'venues#stats', as: 'venue_stats'
    get '/tell-me-more', to: 'profiles#edit', as: 'profile'
    post '/tell-me-more', to: 'profiles#update', as: 'update_profile'
    post '/rsvp/:id', to: 'users#rsvp', as: 'rsvp'
  end

  get '/review/:attendance_id', to: 'feedbacks#rate_event_and_venue', as: 'feedback'
  post '/review/:attendance_id', to: 'feedbacks#submit', as: 'submit_feedback'

  root 'pages#index'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text
#  is_public   :boolean          default(FALSE)
#  start_time  :datetime
#  end_time    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  venue_id    :integer
#
# Indexes
#
#  index_events_on_user_id   (user_id)
#  index_events_on_venue_id  (venue_id)
#
# Foreign Keys
#
#  fk_rails_0cb5590091  (user_id => users.id)
#  fk_rails_f476266cf4  (venue_id => venues.id)
#

class Event < ApplicationRecord
	include Notifiable

	belongs_to :user
	belongs_to :venue
	has_many :invites
	has_many :attendances
	has_many :posts, dependent: :delete_all
	has_many :venue_feedbacks, through: :attendances
	has_many :event_feedbacks, through: :attendances
	has_many :photos, as: :pictureable, dependent: :delete_all

	has_many :attendees, -> { where "rsvp <> 'not_attending'" }, class_name: "Attendance"
	has_many :guests, through: :attendees, source: :user
	has_many :guest_profiles, through: :guests, source: :profile

	accepts_nested_attributes_for :invites

	validates :title, :description, :user_id, presence: true
	validate :future_start_time, if: "start_time.present?"
	validate :duration_must_be_positive
	validate :future_start_time, on: :update, if: "self.start_time_changed?"

	after_create_commit { 
		if start_time && start_time > Time.now
			FeedbackGeneratorJob.perform_in(feedback_opens_at - Time.now, self) if end_time 
		end
	}
	after_update :alert_guests, :update_feedback_period
	before_destroy { notify_many(guests, "event_canceled", self) }

	def duration
		end_time - start_time
	end

	def feedback_opens_at
		end_time + 12.hours unless end_time.nil?
		# Time.now + 10.seconds ## for debugging use only
	end

	def feedback_closes_at
		feedback_opens_at + 1.week
	end

	def generate_feedback_forms
		attendees.each do |attendee|
			EventFeedback.create(attendance_id: attendee.id)
			VenueFeedback.create(attendance_id: attendee.id)
		end
	end

  def display_image
  	if self.venue && self.venue.photos.any?
  		self.venue.default_photo.image_file_name
  	else
      "placeholder.png"
    end
  end

  def venue_recs(ip)
  	request = Geocoder.search(ip).first
  	# request_city = "Montreal" ## for debugging use only
  	if !request || !request.city || request.city.blank?
  		request_city = "Montreal"
  	end
  	best_venues = Venue.near(request_city)
  	best_venues = best_venues.where("capacity > ?", self.invites.count) if self.invites.any?
  	best_venues.limit(3)
  end

	private

		def duration_must_be_positive
			if (start_time.present? && end_time.present?)
				(errors[:base] = "start time and end time conflict") unless (end_time - start_time > 0)
			end
		end

		def future_start_time
			if start_time.present? && start_time < Time.now
				errors[:start_time] = "has already past"
			end
		end

		def alert_guests
			if self.title_changed?
				notify_many(guests, "new_event_title", self)
			elsif self.description_changed?
				notify_many(guests, "new_event_description", self)
			elsif self.venue_id_changed?
				notify_many(guests, "new_event_location", self)
			elsif (self.start_time_changed? || self.end_time_changed?)
				notify_many(guests, "new_event_time", self)
			end
		end

		def update_feedback_period
			if self.end_time_changed? && !self.end_time.nil? && self.end_time > Time.now
				FeedbackGeneratorJob.perform_in(feedback_opens_at - Time.now, self)
			end
		end
	
end

app/controllers/events_controller.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text
#  is_public   :boolean          default(FALSE)
#  start_time  :datetime
#  end_time    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  venue_id    :integer
#
# Indexes
#
#  index_events_on_user_id   (user_id)
#  index_events_on_venue_id  (venue_id)
#
# Foreign Keys
#
#  fk_rails_0cb5590091  (user_id => users.id)
#  fk_rails_f476266cf4  (venue_id => venues.id)
#

class EventsController < ApplicationController
	include EventsHelper
	before_action :authenticate, except: [:public_index]
	before_filter :parse_date_params, only: [:create, :update]

	STEPS = ['basics', 'guests', 'location']

	def public_index
		@events = Event.where(is_public: true)
		@user = current_user
	end

	def index
		@user = current_user
		@events = current_user.events
	end

	# Shows the event page if the user is authorized to see it
	def show
		@event = Event.find(params[:id])
		# skip authentication if event is public
		unless @event.is_public
			# skip verification if user is the event organizer
			if !current_user?(@event.user)
				# check if the current_user has an attendance for this event
				unless already_attending?
					if params[:token] != nil
						verify_invitation
					else
						# lie to the user if they're trying to access an event they shouldn't
						flash[:danger] = "Whoops, we couldn't find that event."
					end
				end
			end
			@attendance = guest_attendance
		end
		@post = Post.new
	end

	def new
		@user = current_user
		@event = Event.new
		@event.venue_id = params[:venue_id] if params[:venue_id]
	end

	def create
		@event = current_user.events.build(event_params)
		if @event.save
			flash[:success] = "Your event has been created!"
			redirect_to user_event_manage_path(current_user, @event, "guests")
		else
			flash[:danger] = "Oops, an error occured. Please try again."
			render 'new'
		end
	end

	def manage
		@user = current_user
		@event = Event.find(params[:event_id])
		if valid_step.present?
      @step = valid_step
      @next_step = next_step
    else
      @step = 'basics'
    end
	end

	# Shows user demographics for the event
	def stats
		@user = current_user
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(event_params)
			if next_step 
		  	redirect_to user_event_manage_path(current_user, @event, params[:step])
		  	flash[:success] = "Your event was updated successfully."
		  else
		  	redirect_to user_event_path(current_user, @event)
		  	flash[:success] = "Awesome, your event is ready."
		  end
		else
		  flash[:danger] = "Some fields are invalid, please check your dates!"
		  redirect_back(fallback_location: :manage)
		end
	end

	def add_guests
		@event = Event.find(params[:event_id])
		if params[:invites]
			emails = params[:invites][:email]
			emails.split(', ').reject(&:empty?).each do |email|
				@invite = @event.invites.create!(email: email)
			end
		end
		if params[:event] && invite_params[:csv_file]
			if Invite.upload(invite_params[:csv_file], @event.id)
			end
		end
		flash[:success] = "Your invitations are now pending."
		redirect_back(fallback_location: :manage)
	end

	def remove_guest
		@invite =Invite.find(params[:id])
		if @invite.destroy
			flash[:success] = "Your invite was deleted."
		else
			flash.now[:danger] = "An error occurred, please try again."
		end
		redirect_back(fallback_location: user_event_manage_path(current_user, params[:event_id], "guests"))
	end

  def send_invites
		@event = Event.find(params[:event_id])
		Invite.where(event_id: @event.id).where(sent_at: nil).each do |invite|
			InviteMailer.invitation(invite).deliver_now
		end
		flash[:success] = "Your invitations have been sent."
		redirect_back(fallback_location: user_event_manage_path(current_user, @event, "guests"))
	end

	def destroy
		@event = Event.find(params[:id])
		if @event.destroy
			redirect_back(fallback_location: user_events_path)
			flash[:success] = "Your event was canceled."
		else
			flash.now[:danger] = "An error occurred, please try again."
			render 'index'
		end
	end

	def preview_venue
		@venue = Venue.find(params[:id])
		@photos = @venue.photos
		render 'venues/show'
	end

	def select_venue
		@event = Event.find(params[:event_id])
		@event.venue_id = params[:id]
		if @event.save(validate: false)
			flash[:success] = "Location saved."
			redirect_to user_event_manage_path(current_user, @event, "location")
		else
			flash[:danger] = "Something went wrong"
			render @event
		end
	end

	def remove_venue
		@event = Event.find(params[:event_id])
		@event.venue_id = nil
		if @event.save(validate: false)
			flash[:success] = "You can now select a new venue"
			redirect_back(fallback_location: :manage)
		else
			flash[:danger] = "Something went wrong"
			render :manage
		end
	end

	private

		def parse_date_params
			if !params[:event][:start_time].blank? && start_s = params[:event][:start_time]
				params[:event][:start_time] = DateTime.strptime(start_s, "%m/%d/%Y %l:%M %p")
			end 
			if !params[:event][:end_time].blank? && end_s = params[:event][:end_time]
				params[:event][:end_time] = DateTime.strptime(end_s, "%m/%d/%Y %l:%M %p")
			end
		end

		def event_params
			params.require(:event).permit(:title, :start_time, :end_time, :description, :is_public, invites_attributes: [:email])
		end

		def invite_params
			params.require(:event).permit(:csv_file)
		end

		def valid_step
	    STEPS.find { |s| s == params[:step].to_s.downcase }
	  end

	  def next_step
	  	current_step_index = STEPS.index(valid_step)
    	next_step = STEPS[current_step_index+1]
	  end

	  def verify_invitation
			@invite = @event.invites.find_by_token(params[:token])
			if valid_token?(@invite)
				@event.attendances.create(user_id: current_user.id, invite_id: @invite.id)
			else
				flash[:danger] = "Woops, that invitation is not valid."
				redirect_to current_user
			end
		end

end

app/helpers/events_helper.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text
#  is_public   :boolean          default(FALSE)
#  start_time  :datetime
#  end_time    :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  venue_id    :integer
#
# Indexes
#
#  index_events_on_user_id   (user_id)
#  index_events_on_venue_id  (venue_id)
#
# Foreign Keys
#
#  fk_rails_0cb5590091  (user_id => users.id)
#  fk_rails_f476266cf4  (venue_id => venues.id)
#

module EventsHelper
	
	def guest_attendance
		@attendance ||= @event.attendances.find_by_user_id(current_user.id)
	end

	def already_attending?
		!guest_attendance.nil?
	end

	def valid_token?(invite)
		# make sure the invitation has not already been used by another user
		@event.attendances.find_by_invite_id(invite.id).nil?
	end

end

app/views/events/_basics.html.erb
<%= render layout: 'form'  do |f| %>

  <div class="flex-content sheet sheet-column">
    <div class="form-group">
      <%= f.label :title do %>
        What is your event called?
      <% end %>
      <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div> <!-- close .form-group -->

    <div class="form-group">
      <%= f.label :description do %>
        Write a short description for your guests
      <% end %>
      <%= f.text_area :description, class: 'form-control' %>
    </div> <!-- close .form-group -->

    <div class="row">
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :start_time %>
          <small class="pull-right"> <%= @event.start_time.to_formatted_s(:long) if @event.start_time %> </small>
          <div class='input-group date' id='datetimepicker-start'>
            <%= f.text_field :start_time, class: 'form-control' %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div> <!-- close .form-group -->
      </div> <!-- close .col -->
      <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :end_time %>
          <small class="pull-right"> <%= @event.end_time.to_formatted_s(:long) if @event.end_time %> </small>
          <div class='input-group date' id='datetimepicker-end'>
            <%= f.text_field :end_time, class: 'form-control' %>
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div> <!-- close .form-group -->
      </div> <!-- close .col -->
    </div> <!-- close .row -->

    <div class="checkbox">
      <%= f.label :is_public do %>
        <%= f.check_box :is_public %> 
        My event is public <span class="label">warning</span>
      <% end %>
    </div> <!-- close .form-group -->

    <div class="form-group">
      <%= f.submit "Update", class: 'btn btn-outline btn-success btn-block-level' %>
      <%= link_to "Continue", user_event_manage_path(current_user, @event.id, @next_step), class: 'btn btn-outline btn-default' %>
    </div> <!-- close .form-group -->

  </div>

<% end %>

<script type="text/javascript">
  $(function () {
      $('#datetimepicker-start').datetimepicker(
        { 
          widgetPositioning: { vertical: 'bottom' }
        }
      );
  });
  $(function () {
      $('#datetimepicker-end').datetimepicker(
        { 
          widgetPositioning: { vertical: 'bottom' }
        }
      );
  });
</script>

app/views/events/_form.html.erb
<div class="form">
	<%= form_for @event, method: :patch, url: user_event_path(current_user, @event.id, step: @step) do |f| %>
	  <% yield f %>
	<% end %>
</div> <!-- close .form -->

<div class="row text-center">
  <%= link_to 'Cancel', user_path(current_user) %>
</div> <!-- close .text-center -->

app/views/events/_guests.html.erb
<%= set_page_title "#{@event.title}" %>

<div class="flex-content sheet sheet-column">
	<div class="row">
		<div class="col-sm-8">

			<% if @event.invites.where(sent_at: nil).any? %>

				<h4>Pending invitations to your event: <%= @event.invites.where(sent_at: nil).count %> </h4>
				<%= link_to "Send now", user_event_send_invites_path(params[:user_username], @event.id), method: :post, class: "btn btn-outline btn-default" %>
				
				<div class="panel panel-default" id="email-panel">
					<div class="panel-body">
						<% @event.invites.where(sent_at: nil).each do |invite| %>
							<h6>
								<%= invite.email %>
								<%= link_to user_event_remove_guest_path(current_user, @event, invite.id), method: :delete, class: 'pull-right' do %>
									<span class="glyphicon glyphicon-remove"></span>
								<% end %>
							</h6>
						<% end %>
					</div>
				</div>

			<% else %>
				<p>You've invited <%= @event.invites.count %> guests so far and have no pending invitations.</p>
			<% end %>

			<%= form_for @event, method: :post, url: user_event_add_guests_path(current_user, @event.id) do |f| %>
				<div class="form-group">
			    <%= f.label :invites, "Add guests" do %>
			      Add guests
			    <% end %>
			    <small>(please enter a comma-separated list of email addresses below)</small>
			    <%= fields_for Invite.new do |i| %>
			    	<%= i.text_field :email, name: "invites[email]", class: "form-control" %>
			    <% end %>
			  </div> <!-- close .form-group -->

			  <div class="form-group">
			    <span class="btn btn-outline btn-default fileinput-button">
			      <i class="icon-plus icon-white"></i>
			      <span><span class="glyphicon glyphicon-paperclip"></span> Upload guest-list</span>
			      <%= f.file_field :csv_file %>
			    </span>
			  </div>

			  <div class="form-group">
			    <%= f.submit "Update", class: 'btn btn-outline btn-success btn-block-level' %>
			    <%= link_to "Continue", user_event_manage_path(current_user, @event.id, @next_step), class: 'btn btn-outline btn-default' %>
			  </div> <!-- close .form-group -->

			<% end %>

		</div>
	</div>
</div>

app/views/events/_location.html.erb
<div class="flex-content sheet sheet-column">
	<div class="row">

		<% if @venue = @event.venue %>	
			
			<div class="col-sm-6">
				Your event will take place at:
				<%= link_to venue_path(@venue.id) do %>
					<h4> <%= @venue.name %> </h4>
				<% end %>

				<% if @venue.photos.any? %>
					<h4>Pictures of the venue:</h4>
					<div class="row">
						<%= render partial: 'photos/venue_thumbnail', collection: @event.venue.photos, as: :photo %>
					</div>
				<% else %>
					<div class="row">
						<div class="col-sm-4">
						  <div class="thumbnail">
						    <%= image_tag "placeholder.png", class: 'img-responsive' %>
						  </div>
						</div>
					</div>
				<% end %>
				<%= link_to "Change venues", user_event_remove_venue_path(@event.user, @event, @venue), class: 'btn btn-outline btn-default', method: :delete %>
				<%= link_to "Complete", event_path(@event), class: 'btn btn-outline btn-success' %>
			</div>

			<div class="col-md-6">
				<%= map(:center => {
			    :latlng => [@venue.latitude, @venue.longitude],
			    :zoom => 15 },
			    :markers => [{
		    		:latlng => [@venue.latitude, @venue.longitude],
		    	}]) %>
		  </div>
				
		<% else %>

			<div class="alert alert-info fade in">
		    You haven't selected a venue yet!
		    <!-- <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> -->
		  </div> <!-- close .flash -->

			<h3>Based on the information you entered, we recommend the following spaces.</h3>

			<div class="row">
				<%= render partial: 'photos/recommendation', collection: @event.venue_recs(remote_ip()), as: :venue %>
			</div>

			<p>We use data entered for your event to generate these recommendations. You can improve the results by completing empty fields.</p>
			<h4>Not what you were looking for? Maybe these will work</h4>

			<div class="row">
				<%= render partial: 'photos/recommendation', collection: Venue.all - @event.venue_recs(remote_ip()), as: :venue %>
			</div>

		<% end %>
	</div>

</div>

app/views/events/_management_nav.html.erb
<div class="nav navbar-btns">
	<%= link_to "basics", user_event_manage_path(@user, @event, "basics"), 
							class: "btn btn-xs btn-outline #{'btn-warning' if @step == 'basics'}" %>
	<%= link_to "guests", user_event_manage_path(@user, @event, "guests"), 
							class: "btn btn-xs btn-outline #{'btn-warning' if @step == 'guests'}" %>
	<%= link_to "venue", user_event_manage_path(@user, @event, "location"), 
							class: "btn btn-xs btn-outline #{'btn-warning' if @step == 'location'}" %>
</div>

app/views/events/_stats_sidebar.html.erb
<div class="col-sm-1 sidebar">

  <div class="sheet sheet-column">
    <div class="row">
      <div class="nav nav-sidebar">
        <div class="text-center">
          <%= image_tag (current_user.profile_picture), class: 'img-thumbnail img-circle', size: '50' %>
          <h6 class="heading"> <%= @event.title %> </h6>
        </div>
        <li></li>
        <li class="text-center">
          <a href="<%= user_path(current_user) %>" class="<%= 'active' if request.fullpath == user_path(current_user) %>">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
            <br>
            <small>Home</small>
          </a> 
        </li>
        <li class="text-center">
          <a href="<%= event_path(@event.id) %>" target="_blank">
            <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
            <br>
            <small>Event</small>
          </a> 
        </li>
        <li class="text-center">
          <a href="<%= user_events_path(current_user) %>">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            <br>
            <small>Back</small>
          </a> 
        </li>
      </div>
    </div>
  </div>

</div>

app/views/events/index.html.erb
<% set_page_title "#{@user.full_name}'s events" %>

<div class="sheet">

	<% if params[:user_username] %>
		<%= render partial: 'users/sidebar' %>
	<% end %>

	<div class="col-sm-9 flex-content sheet sheet-column">
		<% if @events.any? %>
			<div class="row">
				<%= render partial: 'photos/user_event_index', collection: @events, as: :event %>
			</div>
		<% else %>
			<div class="row">
				<%= render partial: 'photos/dummy_event' %>
			</div>
		<% end %>
	</div>
	
</div>

app/views/events/manage.html.erb
<% set_page_title "Edit #{params[:step]} for #{@event.title}" %>

<div class="sheet">
	<%= render partial: 'users/sidebar' %>

	<div class="col-sm-9 flex-content sheet sheet-column">
		<%= render partial: 'events/management_nav' %>
		<!-- declare column width for each step * within * the partial -->
	  <%= render partial: "#{@step}" %>
  </div>

</div>

app/views/events/new.html.erb
<% set_page_title "New Event" %>

<div class="container-fluid form-header">
  <div class="page-header text-center">
    <h2>Create an event</h2>
    <span class="sub">PlaceCard handles event invitations, communication, and planning.</span>
  </div>
</div>

<div class="container padded-container">

  <div class="row">
    <div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">

      <div class="form">
        <%= form_for @event, url: user_events_path, validate: true do |f| %>

        	<div class="form-group">
            <%= f.label :title do %>
              What is your event called?
            <% end %>
            <%= f.text_field :title, autofocus: true, class: 'form-control' %>
          </div> <!-- close .form-group -->


          <div class="row">
            <div class="col-xs-6">
              <div class="form-group">
                <%= f.label :start_time %>
                <div class='input-group date' id='datetimepicker-start'>
                  <%= f.text_field :start_time, class: 'form-control' %>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
                </div>
              </div> <!-- close .form-group -->
            </div> <!-- close .col -->
            <div class="col-xs-6">
              <div class="form-group">
                <%= f.label :end_time %>
                <div class='input-group date' id='datetimepicker-end'>
                  <%= f.text_field :end_time, class: 'form-control' %>
                  <span class="input-group-addon">
                      <span class="glyphicon glyphicon-calendar"></span>
                  </span>
                </div>
              </div> <!-- close .form-group -->
            </div> <!-- close .col -->
          </div> <!-- close .row -->

          <div class="form-group">
            <%= f.label :description do %>
              Write a short description for your guests
            <% end %>
            <%= f.text_area :description, class: 'form-control' %>
          </div> <!-- close .form-group -->

          <div class="checkbox">
    	      <%= f.label :is_public do %>
    	        <%= f.check_box :is_public %> 
    	        My event is public <span class="label">warning</span>
    	      <% end %>
    	    </div> <!-- close .form-group -->

          <div class="form-group">
            <%= f.submit "Create!", class: 'btn btn-primary btn-block-level' %>
          </div> <!-- close .form-group -->
        <% end %>
      </div> <!-- close .form -->

    </div> <!-- close .col -->
  </div> <!-- close .row -->

  <div class="row text-center">
    <%= link_to 'Cancel', user_path(@current_user) %>
  </div> <!-- close .text-center -->
</div>

<script type="text/javascript">
  $(function () {
      $('#datetimepicker-start').datetimepicker(
        { 
          widgetPositioning: { vertical: 'bottom' }
        }
      );
  });
  $(function () {
      $('#datetimepicker-end').datetimepicker(
        { 
          widgetPositioning: { vertical: 'bottom' }
        }
      );
  });
</script>

app/views/events/public_index.html.erb
<% set_page_title "#{@user.full_name}'s events" %>

<div class="sheet">

	<div class="col-sm-9 flex-content sheet sheet-column">
		<% if @events.any? %>
			<div class="row">
				<%= render partial: 'photos/event_index_result', collection: @events, as: :event %>
			</div>
		<% end %>
	</div>
	
</div>

app/views/events/show.html.erb
<%= set_page_title "#{@event.title}" %>

<div class="sheet">

	<div class="col-sm-3 sidebar">

	  <div class="sheet sheet-column">
		  <div class="row">
			  <div class="nav nav-sidebar">
			    
			    <div class="text-center">
			      <%= image_tag (@event.display_image), class: 'img-thumbnail', size: '100' %>
			      <h3> <%= @event.title %> </h3>
			      <p> <%= @event.description %> </p>
			    </div>
			    <li>
			    	<a>
			    		<span>Total invited</span>
			        <span class="pull-right label label-warning"> <%= @event.invites.count %> </span>
			    	</a>
			    </li>
			    <li>
			      <a>
			        <span>Total that have seen invitation</span>
			        <span class="pull-right label label-warning"> <%= @event.attendances.count %> </span>
			      </a> 
			    </li>
			    <li>
			      <a>
			        <span>Total confirmed attending</span>
			        <span class="pull-right label label-warning"> <%= @event.attendees.count %> </span>
			      </a> 
			    </li>
			    <div class="panel panel-default" style="margin: 20px;">
			    	<div class="panel-body">
				    	<% if @event.venue %>
				    		<h4> <%= @event.venue.name %> </h4>
				    	<% else %>
				    		<h5>Location TBD</h5>
				    	<% end %>
				    	<p> <i><%= @event.start_time.to_formatted_s(:long) if @event.start_time %></i> </p>
				    	<p> to <i><%= @event.end_time.to_formatted_s(:long) if @event.end_time %></i> </p>
				    	<p> organized by <%= @event.user.full_name  %> </p>
			    	</div>
			    </div>

			  </div>
		  </div>

		</div>
	</div>

	<div class="col-sm-9 flex-content sheet sheet-column">
		<div class="row">
			<div class="col-md-4">
				<%= render 'posts/form' %>
			</div>
			<% if @event.posts.any? %>
				<%= render partial: 'posts/card', collection: @event.posts(true), as: :post %>
			<% end %>
		</div>
	</div>

</div> <!-- close .sheet -->