config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get '/about', to: 'pages#about', as: 'about'
  get '/join', to: 'users#new', as: 'join'
  post '/join', to: 'users#create', as: 'users'
  
  get '/login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  get '/venues', to: 'venues#public_index', as: 'public_venues' 
  get '/venues/:id', to: 'venues#show', as: 'venue'

  get '/events', to: 'events#public_index', as: 'public_events' 
  resources :events, only: [:show] do
    resources :posts, only: [:create, :update, :destroy]
  end

  resources :users, param: :username, path: '/', except: [:index, :create, :new] do
  	resources :events, except: [:edit, :show] do
      get '/manage/:step', to: 'events#manage', as: 'manage'
      post '/guests', to: 'events#add_guests', as: 'add_guests'
      post '/invite', to: 'events#send_invites', as: 'send_invites'
      delete '/guests/:id', to: 'events#remove_guest', as: 'remove_guest'
      get '/location/:id', to: 'events#preview_venue', as: 'preview_venue'
      post '/location/:id', to: 'events#select_venue', as: 'select_venue'
      delete 'location/:id', to: 'events#remove_venue', as: 'remove_venue'
    end
  	resources :venues, except: [:edit, :show] do
      get '/manage/:step', to: 'venues#manage', as: 'manage'
      post '/photos', to: 'venues#update_photos', as: 'update_photos'
      delete '/photos/:id', to: 'venues#remove_photo', as: 'remove_photo'
      post '/tags', to: 'venues#update_tags', as: 'update_tags'
    end
    resources :photos, only: [:create, :destroy]
    get '/events/:id', to: 'events#stats', as: 'event_stats'
    get '/venues/:id', to: 'venues#stats', as: 'venue_stats'
    get '/tell-me-more', to: 'profiles#edit', as: 'profile'
    post '/tell-me-more', to: 'profiles#update', as: 'update_profile'
    post '/rsvp/:id', to: 'users#rsvp', as: 'rsvp'
  end

  get '/review/:attendance_id', to: 'feedbacks#rate_event_and_venue', as: 'feedback'
  post '/review/:attendance_id', to: 'feedbacks#submit', as: 'submit_feedback'

  root 'pages#index'

end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  website     :string
#  latitude    :float
#  longitude   :float
#  capacity    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  city        :string
#  street      :string
#  suite_no    :string
#
# Indexes
#
#  index_venues_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_ad8f6027f0  (user_id => users.id)
#

class Venue < ApplicationRecord
	include Notifiable
	include Filterable

	belongs_to :user
	has_many :events, dependent: :nullify
	has_many :venue_feedbacks, through: :events
	has_many :photos, as: :pictureable, dependent: :destroy
	has_many :venue_tags
	has_many :tags, through: :venue_tags
	has_many :organizers, through: :events, source: :user
	has_many :organizer_profiles, through: :organizers, source: :profile

	accepts_nested_attributes_for :photos, :tags

	validates :user_id, :name, :city, :street, :capacity, presence: true
	validates :address, presence: true

	geocoded_by :address
	after_validation :geocode

	# `categories` is an array of satisfactory categories
	scope :category, -> (categories) { Venue.includes(:tags).where("tags.name": categories) }
	# `tag` is a single parameter (no arrays)
	scope :tagged, -> (tag) { Tag.find_by_name("#{tag}").venues if Tag.find_by_name("#{tag}") }

	def address
    address = ""
    if !suite_no.blank?
    	address += suite_no + "-"
    end
	if !street.blank? && !city.blank?
		address += [street,city].join(", ")
	end
  end

  def default_photo
  	photos.where(is_profile: true).first || photos.first
  end

	def self.search(search)
		if search
			near(search, 100)
			# where("description LIKE ?", "%#{search}%") @TODO fix this or elaborate search
	  else
	    all
	  end
	end

end

app/controllers/venues_controller.rb
# == Schema Information
#
# Table name: venues
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  website     :string
#  latitude    :float
#  longitude   :float
#  capacity    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  city        :string
#  street      :string
#  suite_no    :string
#
# Indexes
#
#  index_venues_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_ad8f6027f0  (user_id => users.id)
#

class VenuesController < ApplicationController
	before_action :authenticate, except: [:public_index, :show]

	STEPS = ['basics', 'photos', 'location', 'amenities']
	
	def public_index
		@venues = Venue.all
		if params[:search]
			@previous_search = params[:search]
			@venues = Venue.search(params[:search])
		end
		if !params[:guests].blank?
			@venues = @venues.where("capacity > ?", params[:guests])
		end
		if params[:tags]
			@venues = @venues.filter({tagged: params[:tags]})
		end
		if params[:category]
			# find the intersection of venues with appropriate category and tags
			@venues &= Venue.category(params[:category])
		end
	end

	def index
		if @user = User.find_by_username(params[:user_username])
			@venues = @user.venues
		end
	end

	def show
		@venue = Venue.find(params[:id])
		@photos = @venue.photos.all
	end

	def new
		@user = current_user
		@venue = Venue.new
		@photo = @venue.photos.build
	end

	def create
		@venue = current_user.venues.build(venue_params)
		if @venue.save
			flash[:success] = "Success!"
			redirect_to user_venue_manage_path(current_user, @venue, "basics")
		else
			flash[:danger] = "Oops, an error occurred. Please try again."
			render 'new'
		end
	end

	def manage
		@venue = Venue.find(params[:venue_id])
		@types = Tag.where(name: Tag::VENUE_TYPES )
		@user = current_user
		if valid_step.present?
      @step = valid_step
      @next_step = next_step
    else
      @step = 'basics'
    end
	end

	def stats
		@user = current_user
		@venue = Venue.find(params[:id])
	end

	def update
		@venue = Venue.find(params[:id])
		if params[:venue] && !@venue.update_attributes(venue_params)
			flash.now[:danger] = "Oops, an error occurred. Try again?"
		  render 'manage'
		end
		flash[:success] = "Your changes have been saved."
		redirect_to user_venue_manage_path(current_user, @venue.id, params[:step])
  end

  def update_photos
  	@venue = Venue.find(params[:venue_id])
		if photos = params[:venue][:photos]
			photos.each do |image|
				if @photo = @venue.photos.create!(image_file_name: image, owner_id: current_user.id)
					respond_to do |format|
						# immediately render the new photo
						format.js { render file: "photos/new_venue"}
					end
				end
			end
		end
  end

 	def remove_photo
  	@photo = Photo.find(params[:id])
		if @photo.destroy
			flash[:success] = "Your photo was successfully deleted."
			redirect_to user_venue_manage_path(current_user, params[:venue_id], "photos")
		else
			flash.now[:danger] = "An error occurred, please try again."
		end
  end

  def update_tags
  	@venue = Venue.find(params[:venue_id])
  	@venue_tags = @venue.venue_tags
  	default_types = Tag.where(name: Tag::VENUE_TYPES)
  	# The venue owner has updated the type of their venue
  	if params[:venue_type] && !@venue_tags.include?(tag_id: params[:venue_type])
  		# destroy the old tag association(s) then add the new one
  		@venue_tags.where(tag_id: default_types).destroy_all
  		@venue.venue_tags.create(tag_id: params[:venue_type])
  	end
  	default_features = Tag.where(name: Tag::VENUE_FEATURES)
  	if params[:venue_features] && params[:venue_features].any?
  		# destroy all associations to features and recreate
  		@venue_tags.where(tag_id: default_features).destroy_all
  		new_tags = Tag.where(name: params[:venue_features])
  		new_tags.each do |tag|
  			@venue.venue_tags.create(tag_id: tag.id)
  		end
  	end
  	flash[:success] = "Awesome, your venue was tagged."
  	redirect_to :back
  end

  def continue
		if next_step 
	  	redirect_to user_venue_manage_path(current_user, @venue, next_step)
	  else
	  	redirect_to user_venue_path(current_user, @venue)
	  	flash[:success] = "Awesome, your venue is complete."
	  end
  end

	def destroy
		@venue = Venue.find(params[:id])
		if @venue.destroy
			redirect_back(fallback_location: user_venues_path)
			flash[:success] = "Your venue was successfully deleted."
		else
			flash.now[:danger] = "An error occurred, please try again."
			render 'index'
		end
	end

	private

		def venue_params
			params.require(:venue).permit(:name, :description, :website, :city, :street, :suite_no, :capacity)
		end

		def photos_params
			params.require(:venue).permit(photos_attributes: [:image_file_name])
		end

		def valid_step
	    STEPS.find { |s| s == params[:step].to_s.downcase }
	  end

	  def next_step
	  	current_step_index = STEPS.index(valid_step)
    	next_step = STEPS[current_step_index+1]
	  end

end

app/views/venues/_amenities.html.erb
<div class="sheet sheet-row">

  <div class="col-sm-6">
    <%= form_tag action: 'update_tags', method: 'post' do %>

      <h4>Please tell us more about your venue</h4>

      <div class="form-group">
        <label>What kind of space are you listing?</label>
        <% @types.each do |type| %>
          <div class="radio">
            <label>
              <%= radio_button_tag :venue_type, type.id %>
              <%= type.name.titleize %>
            </label>
          </div>
        <% end %>
      </div>

      <div class="form-group">
        <label>How accessible is your space?</label>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :wheelchair_accessible %> It's wheelchair accessible.
          </label>
        </div>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :restrooms %> It has clean washrooms for all genders.
          </label>
        </div>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :catering %> It offers a variety of catering options.
          </label>
        </div>
      </div>

      <div class="form-group">
        <label>What other perks does your venue have?</label>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :kitchen_dining %> It has a full kitchen and dining space.
          </label>
        </div>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :performances %> It's suitable for performances.
          </label>
        </div>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :security %> It has 24-hour security.
          </label>
        </div>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :licensed_bar %> It has a licensed bar.
          </label>
        </div>
        <div class="checkbox">
          <label>
            <%= check_box_tag "venue_features[]", :onsite_cleaning %> There are janitors on-site.
          </label>
        </div>
      </div>

      <div class="form-group">
        <%= submit_tag "Save changes", class: 'btn btn-outline btn-default btn-block-level' %>
        <%= link_to "Complete", venue_path(@venue), class: 'btn btn-outline btn-success' %>
      </div> <!-- close .field -->

    <% end %>

  </div>

  <div class="col-sm-6">
    <% if @venue.tags.any? %>
      <div class="panel panel-default">
        <div class="panel-body">
          <p>Current tags: </p>
          <% @venue.tags.each do |tag| %>
            <span class="label label-primary" id="tag"> <%= tag.name.humanize %> </span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/venues/_basics.html.erb
<%= render layout: 'form'  do |f| %>

  <div class="flex-content sheet sheet-column">

    <div class="form-group">
      <%= f.label :name, "Venue name" %>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div> <!-- close .field -->

    <div class="form-group">
      <%= f.label :description, "Please include a brief description of the venue." %>
      <%= f.text_area :description, class: 'form-control' %>
    </div> <!-- close .form-group -->

    <div class="form-group">
      <div class="row">
        <div class="col-sm-7">
          <%= f.label :website %>
          <%= f.text_field :website, class: 'form-control' %>
        </div>
        <div class="col-sm-5">
          <%= f.label :capacity %>
          <%= f.text_field :capacity, class: 'form-control' %>
        </div>
      </div>
    </div> <!-- close .form-group -->

    <div class="form-group">
      <%= f.submit "Save changes", class: 'btn btn-outline btn-success btn-block-level' %>
      <%= link_to "Continue", user_venue_manage_path(current_user, @venue.id, @next_step), class: 'btn btn-outline btn-default' %>
    </div> <!-- close .form-group -->


  </div>

<% end %>

app/views/venues/_form.html.erb
<%= form_for @venue, method: :patch, url: user_venue_path(current_user, @venue.id, step: @step) do |f| %>
  <% yield f %>
<% end %>

<div class="row text-center">
  <%= link_to 'Cancel', user_path(current_user) %>
</div> <!-- close .text-center -->

app/views/venues/_location.html.erb
<div class="sheet sheet-row">
  <div class="col-md-6">
    
    <h4> <%= @venue.name %> </h4>
    <%= form_for @venue, method: :patch, url: user_venue_path(current_user, @venue.id, step: @step) do |f| %>
      
      <%= f.label :city, "So, where is it?" %>
      <div class="radio">
        <label>
          <%= f.radio_button :city, "Vancouver, BC", class: "" %>
          Vancouver
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :city, "Toronto, ON", class: "" %>
          Toronto
        </label>
      </div>
      <div class="radio">
        <label>
          <%= f.radio_button :city, "Montreal, QC", class: "" %>
          Montreal
        </label>
      </div>

      <div class="row">
        <div class="col-sm-3">
          <div class="form-group">
            <%= f.label :suite_no, "Suite" %>
            <%= f.text_field :suite_no, class: 'form-control' %>
          </div>
        </div>
        <div class="col-sm-9">
          <div class="form-group">
            <%= f.label :street, "Street address" %>
            <%= f.text_field :street, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= submit_tag "Save changes", class: 'btn btn-outline btn-success btn-block-level' %>
        <%= link_to "Continue", user_venue_manage_path(current_user, @venue.id, @next_step), class: 'btn btn-outline btn-default' %>
      </div> <!-- close .form-group -->

    <% end %>

    <div class="row text-center">
      <%= link_to 'Cancel', user_path(current_user) %>
    </div> <!-- close .text-center -->

  </div>

  <div class="col-md-6">
    <%= map(:center => {
          :latlng => [@venue.latitude, @venue.longitude],
          :zoom => 15 },
          :markers => [{
            :latlng => [@venue.latitude, @venue.longitude],
          }]
    ) %>
  </div>

</div>

app/views/venues/_management_nav.html.erb
<div class="nav navbar-btns">
	<%= link_to "basics", user_venue_manage_path(@user, @venue, "basics"), 
							class: "btn btn-xs btn-outline btn-default #{'btn-warning' if @step == 'basics'}" %>
	<%= link_to "images", user_venue_manage_path(@user, @venue, "photos"), 
							class: "btn btn-xs btn-outline btn-default #{'btn-warning' if @step == 'photos'}" %>
	<%= link_to "location", user_venue_manage_path(@user, @venue, "location"), 
							class: "btn btn-xs btn-outline btn-default #{'btn-warning' if @step == 'location'}" %>
	<%= link_to "tags", user_venue_manage_path(@user, @venue, "amenities"), 
							class: "btn btn-xs btn-outline btn-default #{'btn-warning' if @step == 'amenities'}" %>
</div>

app/views/venues/_photos.html.erb
<div class="flex-content sheet sheet-column">
	<div id="photos">
		<div class="row" id="js-photo-cards">
			<%= render partial: 'photos/venue_upload', collection: @venue.photos, as: :photo %>
		</div>
	</div>

	<% if @venue.photos.count > 5 %>
		<div class="alert alert-info">
			You can upload a maximum of 6 photos
		</div>
	<% else %>
		<%= form_for @venue, method: :post, url: user_venue_update_photos_path(current_user, @venue.id) do |f| %>

			<div class="form-group">
				<span class="btn btn-outline btn-success fileinput-button">
			    <span class="glyphicon glyphicon-paperclip"></span>
			    <span>Add files</span>
			    <%= f.file_field "photos", multiple: true, id: "jq_photo" %>
			  </span>
			  <%= link_to "Continue", user_venue_manage_path(current_user, @venue.id, @next_step), class: 'btn btn-outline btn-default' %>
			</div>

		<% end %>
	<% end %>

	<div class="row text-center">
	  <%= link_to 'Cancel', user_path(current_user) %>
	</div> <!-- close .text-center -->

</div>

app/views/venues/_stats_sidebar.html.erb
<div class="col-sm-1 sidebar">

  <div class="sheet sheet-column">
    <div class="row">
      <div class="nav nav-sidebar">
        <div class="text-center">
          <%= image_tag (current_user.profile_picture), class: 'img-thumbnail img-circle', size: '50' %>
          <h6 class="heading"> <%= @venue.name %> </h6>
        </div>
        <li></li>
        <li class="text-center">
          <a href="<%= user_path(current_user) %>" class="<%= 'active' if request.fullpath == user_path(current_user) %>">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
            <br>
            <small>Home</small>
          </a> 
        </li>
        <li class="text-center">
          <a href="<%= venue_path(@venue.id) %>" target="_blank">
            <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
            <br>
            <small>Venue</small>
          </a> 
        </li>
        <li class="text-center">
          <a href="<%= user_venues_path(current_user) %>">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
            <br>
            <small>Back</small>
          </a> 
        </li>
      </div>
    </div>
  </div>

</div>

app/views/venues/index.html.erb
<% set_page_title "#{@user.full_name}'s venues" %>

<div class="sheet">

	<% if params[:user_username] %>
		<%= render partial: 'users/sidebar' %>
	<% end %>

	<div class="col-sm-9 flex-content sheet sheet-column">
		<% if @venues.any? %>
			<div class="row">
				<%= render partial: 'photos/user_venue_index', collection: @venues, as: :venue %>
			</div>
		<% else %>
			<div class="row">
				<%= render partial: 'photos/dummy_venue' %>
			</div>
		<% end %>

	</div>
</div>

app/views/venues/manage.html.erb
<% set_page_title "Edit #{params[:step]} for #{@venue.name}" %>

<div class="sheet">
	
	<!-- sidebar is 3-col wide -->
	<%= render partial: 'users/sidebar' %>

	<div class="col-sm-9 flex-content sheet sheet-column">	
		<%= render partial: 'venues/management_nav' %>
		<!-- declare column width for each step * within * the partial -->
		<%= render partial: "#{@step}" %>		
  </div>
</div>

app/views/venues/new.html.erb
<% set_page_title "List your venue" %>

<div class="container-fluid form-header">
  <div class="page-header text-center">
    <h2>List your space</h2>
    <span class="sub">All venues on PlaceCard are publicly visible by default.</span>
  </div>
</div>

<div class="container padded-container">
  <div class="row">
    <div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">

      <div class="form">
        <%= form_for @venue, url: user_venues_path, validate: true do |f| %>

          <div class="form-group">
            <%= f.label :name do %>
              What is the name of your venue?
            <% end %>
            <%= f.text_field :name, autofocus: true, class: 'form-control' %>
          </div> <!-- close .form-group -->

          <div class="form-group">
            <label> In what city is your venue located? </label> <br>
            <div class="btn-group" data-toggle="buttons">
              <label class="btn btn-info">
                <%= f.radio_button :city, "Vancouver, BC" %> Vancouver
              </label>
              <label class="btn btn-info">
                <%= f.radio_button(:city, "Toronto, ON") %> Toronto
              </label>
              <label class="btn btn-info">
                <%= f.radio_button(:city, "Montreal, QC") %> Montreal
              </label>
            </div>
          </div> <!-- close .form-group -->

          <div class="row">
            <div class="col-xs-2">
              <div class="form-group">
                <%= f.label :suite_no, "Suite" %>
                <%= f.text_field :suite_no, class: 'form-control' %>
              </div> <!-- close .form-group -->
            </div>
            <div class="col-xs-10">
              <div class="form-group">
                <%= f.label :street, "Street address" %>
                <%= f.text_field :street, class: 'form-control' %>
              </div> <!-- close .form-group -->
            </div>
          </div> <!-- close .row -->

          <div class="form-group">
            <%= f.label :capacity, "What is the maximum capacity of your venue?" %>
            <%= f.text_field :capacity, class: 'form-control' %>
          </div> <!-- close .form-group -->

          <div class="form-group">
            <%= f.label :website, "Does your venue have a website?" %>
            <%= f.text_field :website, class: 'form-control' %>
          </div> <!-- close .form-group -->

          <div class="form-group">
            <%= f.submit "Submit my space", class: 'btn btn-primary btn-block-level' %>
          </div> <!-- close .form-group -->
        <% end %>
      </div> <!-- close .form -->

    </div> <!-- close .col -->
  </div> <!-- close .row -->

  <div class="row text-center">
    <%= link_to 'Cancel', user_path(@current_user) %>
  </div> <!-- close .text-center -->
</div>

app/views/venues/public_index.html.erb
<div class="sheet sheet-column">
	<div class="navbar nav-search form-header">
		<div class="flex-content container-fluid">
			<%= form_tag url_for(controller: "venues", action: "public_index"), method: "get", class: "navbar-form" do %>
				
				<div class="col-sm-4">
					<label>Limit my results to this type of venue.</label>
					<br>
					<% Tag.where(name: Tag::VENUE_TYPES).each do |type| %>
			            <label class="checkbox-inline">
			              <%= check_box_tag "category[]", type.name %>
			              <%= type.name.titleize %>
			            </label>
	       			<% end %>
	      </div>

	      <div class="col-sm-6">
	      	<label>Limit my results to venues with the following amenities.</label>
			<br>
			<% Tag.where(name: Tag::VENUE_FEATURES).each do |type| %>
			<div class="col-sm-4">
	            <label class="checkbox-inline">
	              <%= check_box_tag "tags[]", type.name %>
	              <%= type.name.titleize %>
	            </label>
            </div>
	        <% end %>
	      </div>

	      <%= hidden_field_tag :search, @previous_search %>

	      <div class="col-sm-2">
      		<%= submit_tag "Filter", class: "btn btn-primary" %>
      		<%= link_to "Reset", public_venues_path, class: "btn btn-warning" %>
	      </div>

			<% end %>

		</div>
	</div>

	<div class="flex-content sheet sheet-column">
		<% if @venues.any? %>
			<div class="row">
				<%= render partial: 'photos/venue_index_result', collection: @venues, as: :venue %>
			</div>
		<% end %>
	</div>
</div>

app/views/venues/show.html.erb
<%= set_page_title "#{@venue.name}" %>

<div class="flex-content">
	<div class="col-md-11 sheet sheet-row">

		<div class="col-md-6">

			<h3> <%= @venue.name %> </h3>
			<hr>
			 <span class="glyphicon glyphicon-map-marker"></span> Address: <br><%= @venue.address %> <br>
			 <span class="glyphicon glyphicon-th"></span> Capacity: <%= @venue.capacity %> </li><br>
			 <span class="glyphicon glyphicon-globe"></span> Web: <a href="<%= @venue.website %>">external link</a>	

			<hr>
			<p> <%= @venue.description %> </p>
			<hr>
			<% if @photos.any? %>
				<h4>Pictures of the venue:</h4>
				<div class="row">
					<%= render partial: 'photos/venue_thumbnail', collection: @photos, as: :photo %>
				</div>
			<% end %>

		</div> <!-- col-md-6 -->

		<div class="col-md-6">
			<%= map(:center => {
		    :latlng => [@venue.latitude, @venue.longitude],
		    :zoom => 15 },
		    :markers => [{
	    		:latlng => [@venue.latitude, @venue.longitude],
	    	}]) %>
			
				<div class="text-center">
					<!-- The user came from their management page -->
		    	<% if current_user?(@venue.user) %>
		    		<h5>Just checking in?</h5>
		    		<%= link_to "See stats", user_venue_stats_path(current_user, params[:id], @venue.id),
		    								 class: 'btn btn-primary' %>
					<!-- The user came from their management page -->
		    	<% elsif current_user && params[:event_id] %>
		    		<h5>I'll take it.</h5>
		    		<%= link_to "Update my event", user_event_select_venue_path(current_user, params[:event_id], @venue.id), method: :post,
		    								 class: 'btn btn-primary' %>
		    	<!-- The user is logged in and browsing -->
		    	<% elsif current_user && params[:id] %>
		    		<h5>Sound good?</h5>
		    		<%= link_to "Use this space", new_user_event_path(current_user, params[:event_id], venue_id: @venue.id),
		    								 class: 'btn btn-primary' %>
		    	<!-- The user is not logged in -->
		    	<% else %>
	    			<h5>Want to use this space for your event?</h5>
	    			<%= link_to "Sign up", join_path, class: 'btn btn-primary' %>
		    	<% end %>
		    </div> <!-- close .text-center -->
		</div> <!-- close .col-md-6 -->
	</div>

</div>

app/views/venues/stats.html.erb
<% set_page_title "Data for #{@venue.name}" %>

<div class="sheet">
	<%= render partial: 'stats_sidebar' %>

	<div class="col-sm-11 flex-content sheet sheet-column">	
		
		<div class="row">
			<div class="col-sm-4">
				<div class="panel panel-warning panel-chart">
					<div class="panel-heading">Are they public events?</div>
					<div class="panel-body">
						<%= pie_chart @venue.events.group(:is_public).count %>
					</div>
				</div>
			</div>
			<div class="col-sm-8">
				<div class="panel panel-warning panel-chart">
					<div class="panel-heading">Event frequency by month</div>
					<div class="panel-body">
						<%= column_chart @venue.events.group_by_month(:start_time, format: "%B").count %>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12">
				<div class="panel panel-warning panel-chart">
					<div class="panel-heading">Guest traction by event</div>
					<div class="panel-body">
						<%= line_chart @venue.events.map { |event|
								    {name: event.title, data: event.attendances.group_by_day(:created_at, format: "%c").count}
								} %>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-8">
				<div class="panel panel-warning panel-chart">
					<div class="panel-heading">Popular event times (external)</div>
					<div class="panel-body">
						<%= area_chart Event.unscoped.where(venue_id: @venue.id).group_by_hour(:start_time, format: "%c").count %>
					</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="panel panel-warning panel-chart">
					<div class="panel-heading">Event organizers by astrological sign</div>
					<div class="panel-body">
						<%= pie_chart @venue.organizer_profiles.group(:astrology).count %>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>